import { jsPDF } from "jspdf";

type CharacterEntry = {
  name: string;
  mentions: number;
  role: string;
};

type AnalysisResult = {
  overallScore: number;
  grammar: number;
  plot: number;
  characters: number;
  pacing: number;
  originality: number;
  emotionalImpact: number;
  strengths: string[];
  weaknesses: string[];
  suggestions: string[];
  summary?: string;
  themes?: string[];
  characterList?: CharacterEntry[];
  timeline?: string[];
  readability?: {
    flesch_reading_ease: number;
    grade_level: number;
    word_count: number;
    sentence_count: number;
    average_sentence_length: number;
  };
};

export const generateStoryReport = async (story: string, result: AnalysisResult) => {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 20;

  // Helper for page numbers and footer
  const addHeaderFooter = (pageNumber: number) => {
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150, 150, 150);
    
    // Footer
    doc.text("Generated by Story Analyzer", margin, pageHeight - 10);
    doc.text(`Page ${pageNumber}`, pageWidth - margin - 10, pageHeight - 10);
    
    // Header Line
    doc.setDrawColor(240, 240, 240);
    doc.line(margin, 25, pageWidth - margin, 25);
  };

  let currentPage = 1;
  addHeaderFooter(currentPage);

  // Logo / Branding
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(99, 102, 241); // Indigo-500
  doc.text("STORY ANALYZER", margin, 20);
  
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(new Date().toLocaleDateString(), pageWidth - margin - 15, 20);
  
  y = 35;

  // Title / First few words of story
  const title = story.split(" ").slice(0, 6).join(" ") + "...";
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 41, 59); // Slate-800
  doc.text("Analysis Report", margin, y);
  y += 10;
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100, 116, 139); // Slate-500
  doc.text(`Source: ${title}`, margin, y);
  y += 15;

  // Overall Score Badge
  doc.setFillColor(248, 250, 252); // Slate-50
  doc.roundedRect(margin, y, pageWidth - margin * 2, 25, 3, 3, "F");
  
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(71, 85, 105);
  doc.text("OVERALL SCORE", margin + 10, y + 16);
  
  doc.setFontSize(22);
  doc.setTextColor(99, 102, 241);
  doc.text(`${result.overallScore}/10`, pageWidth - margin - 35, y + 17);
  y += 35;

  // Helper to check for page overflow
  const checkOverflow = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - 25) {
      doc.addPage();
      currentPage++;
      addHeaderFooter(currentPage);
      y = 35;
      return true;
    }
    return false;
  };

  // Summary
  if (result.summary) {
    checkOverflow(20);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 41, 59);
    doc.text("Executive Summary", margin, y);
    y += 8;
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(51, 65, 85);
    const summaryLines = doc.splitTextToSize(result.summary, pageWidth - margin * 2);
    doc.text(summaryLines, margin, y);
    y += summaryLines.length * 6 + 10;
  }

  // Scores Grid
  checkOverflow(30);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Metrics", margin, y);
  y += 8;
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const scores = [
    ["Grammar", result.grammar],
    ["Plot", result.plot],
    ["Characters", result.characters],
    ["Pacing", result.pacing],
    ["Originality", result.originality],
    ["Emotional Impact", result.emotionalImpact]
  ];
  
  scores.forEach(([label, score], i) => {
    const col = i % 2 === 0 ? margin : margin + 80;
    doc.text(`${label}:`, col, y);
    doc.setFont("helvetica", "bold");
    doc.text(`${score}/10`, col + 40, y);
    doc.setFont("helvetica", "normal");
    if (i % 2 !== 0) y += 6;
  });
  y += 10;

  // Detailed Sections
  const addBlockSection = (title: string, items: string[], color: [number, number, number]) => {
    if (items.length === 0) return;
    checkOverflow(20);
    y += 5;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(color[0], color[1], color[2]);
    doc.text(title, margin, y);
    y += 8;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(51, 65, 85);
    items.forEach(item => {
      const lines = doc.splitTextToSize(`• ${item}`, pageWidth - margin * 2);
      checkOverflow(lines.length * 6);
      doc.text(lines, margin, y);
      y += lines.length * 6 + 2;
    });
    y += 5;
  };

  addBlockSection("Strengths", result.strengths, [16, 185, 129]); // Emerald-600
  addBlockSection("Improvements", result.weaknesses, [225, 29, 72]); // Rose-600
  addBlockSection("Suggestions", result.suggestions, [99, 102, 241]); // Indigo-600

  // Themes
  if (result.themes && result.themes.length > 0) {
    checkOverflow(20);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 41, 59);
    doc.text("Themes", margin, y);
    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(result.themes.join(", "), margin, y);
    y += 12;
  }

  // Character List
  if (result.characterList && result.characterList.length > 0) {
    checkOverflow(25);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Character Analysis", margin, y);
    y += 8;
    result.characterList.forEach(char => {
      checkOverflow(6);
      doc.setFont("helvetica", "bold");
      doc.text(char.name, margin, y);
      doc.setFont("helvetica", "normal");
      doc.text(` - ${char.role} (${char.mentions} mentions)`, margin + 40, y);
      y += 6;
    });
    y += 10;
  }

  // Readability
  if (result.readability) {
    checkOverflow(25);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Readability Metrics", margin, y);
    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const r = result.readability;
    doc.text(`Flesch Ease: ${r.flesch_reading_ease}/100`, margin, y);
    doc.text(`Grade Level: ${r.grade_level}`, margin + 60, y);
    doc.text(`Avg Sentence: ${r.average_sentence_length} words`, margin + 110, y);
    y += 6;
    doc.text(`Word Count: ${r.word_count}`, margin, y);
    doc.text(`Sentence Count: ${r.sentence_count}`, margin + 60, y);
    y += 15;
  }

  doc.save("story-analysis-report.pdf");
};

export const generateComparisonReport = async (
  storyA: string, resultA: AnalysisResult,
  storyB: string, resultB: AnalysisResult,
  comparisonSummary: string
) => {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 20;

  const addHeaderFooter = (pageNumber: number) => {
    doc.setFontSize(8); doc.setTextColor(150);
    doc.text("Story Comparison Report", margin, pageHeight - 10);
    doc.text(`Page ${pageNumber}`, pageWidth - margin - 10, pageHeight - 10);
  };

  addHeaderFooter(1);
  doc.setFontSize(22); doc.setFont("helvetica", "bold"); doc.setTextColor(30);
  doc.text("Story Comparison Report", margin, y);
  y += 15;

  // AI Comparison Summary
  doc.setFontSize(14); doc.text("Executive Comparison Summary", margin, y);
  y += 8;
  doc.setFontSize(10); doc.setFont("helvetica", "normal");
  const compLines = doc.splitTextToSize(comparisonSummary, pageWidth - margin * 2);
  doc.text(compLines, margin, y);
  y += compLines.length * 6 + 15;

  // Comparison Table Header
  const colWidth = (pageWidth - margin * 2) / 2;
  doc.setFontSize(12); doc.setFont("helvetica", "bold");
  doc.text("Story A", margin + 10, y);
  doc.text("Story B", margin + colWidth + 10, y);
  y += 5;
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Metrics comparison
  const addCompareRow = (label: string, valA: any, valB: any) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setFontSize(9); doc.setFont("helvetica", "bold");
    doc.text(label, pageWidth / 2, y, { align: "center" });
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.text(String(valA), margin + 10, y);
    doc.text(String(valB), margin + colWidth + 10, y);
    y += 10;
  };

  addCompareRow("Overall Score", `${resultA.overallScore}/10`, `${resultB.overallScore}/10`);
  addCompareRow("Word Count", resultA.readability?.word_count || "N/A", resultB.readability?.word_count || "N/A");
  addCompareRow("Flesch Ease", resultA.readability?.flesch_reading_ease || "N/A", resultB.readability?.flesch_reading_ease || "N/A");
  addCompareRow("Grade Level", resultA.readability?.grade_level || "N/A", resultB.readability?.grade_level || "N/A");

  doc.save("story-comparison-report.pdf");
};
